name: Simple CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2  # Checkout the repository
    - name: Print a message
      run: echo "This is a simple GitHub Actions project"
    - name: List files
      run: ls -R
      
